name: Python application

on:
  push:
    branches: 
      - "*"  # Run on all branches for any push events
  pull_request:
    branches: 
      - "*"  # Run on all branches for any pull request events

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask_cors
          pip install -r requirements.txt  # Install dependencies from your requirements.txt file

      - name: Start Flask server
        run: |
          flask run --host=0.0.0.0 &
        env:
          FLASK_APP: server.py #update server.py
        working-directory: ${{ github.workspace }}SWEN732-team1/PCP/server
    
      - name: Run unit tests
        run: |
          python -m unittest discover tests -v
        working-directory: ${{ github.workspace }}SWEN732-team1/PCP/server #okay  
