# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]  # Consider changing "master" to "main" if your default branch is named "main"
  pull_request:
    branches: [ "master" ]  # Same as above, consider the name of your default branch

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r reqruirements.txt  # Install other necessary packages

    - name: Run unit tests
      run: |
        python -m coverage run --data-file=coverage_unittest.data --source=src/db,tests -m unittest -v

