# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]  # Consider changing "master" to "main" if your default branch is named "main"
  pull_request:
    branches: [ "master" ]  # Same as above, consider the name of your default branch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r reqruirements.txt  # Note the typo in 'reqruirements.txt' is preserved as per your file name
      working-directory: SWEN732-team1/PCP/server  # This specifies the correct directory where your requirements file is
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      working-directory: SWEN732-team1/PCP/server  # Adjust this if you want flake8 to lint the code in this specific directory
    - name: Test with pytest
      run: pytest
      working-directory: SWEN732-team1/PCP/server  # Adjust this if you want pytest to run tests in this specific directory
